### Получение всех
GET http://localhost:3000/notes

### Получение по id
GET http://localhost:3000/notes/1

### Создание
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Планы на релиз",
  "content": "## Задачи\n1. Собрать сборку УК **3.0.12.240**\n2. Сделать *тесты установки*",
  "tags": ["работа", "срочно", "сборка"]
}

### Обновление
PUT http://localhost:3000/notes/3
Content-Type: application/json

{
  "title": "Релиз",
  "content": "# Обновленный заголовок\n\nОтправка на FTP",
  "tags": ["работа", "срочно", "сборка", "сделано"]
}

### Удаление
DELETE http://localhost:3000/notes/3

### Ошибка 404
GET http://localhost:3000/notes/3

### Ошибка 500
GET http://localhost:3000/test-500