### Получение всех
GET http://localhost:3000/notes

### Получение по id
GET http://localhost:3000/notes/2

### Создание
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Планы на релиз",
  "content": "## Задачи\n1. Собрать сборку УК **3.0.12.240**\n2. Сделать *тесты установки*",
  "tags": ["работа", "срочно", "сборка"]
}

### Обновление
PUT http://localhost:3000/notes/7
Content-Type: application/json

{
  "title": "Тест",
  "content": "# Обновленный заголовок\n\nТестик",
  "tags": ["работа", "срочно", "сделано"],
  "isArchived": false
}

### Удаление
DELETE http://localhost:3000/notes/7
